services:
  - type: web
    name: fasel-aquarium
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: APP_URL
        sync: false

      - key: APP_KEY
        sync: false

      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        sync: false

      - key: DB_PORT
        sync: false

      - key: DB_DATABASE
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: MIDTRANS_SERVER_KEY
        sync: false

      - key: MIDTRANS_CLIENT_KEY
        sync: false

      - key: MIDTRANS_IS_PRODUCTION
        value: "false"

      - key: MIDTRANS_IS_SANITIZED
        value: "true"

      - key: MIDTRANS_IS_3DS
        value: "true"

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      - key: SUPABASE_PROFILE_BUCKET
        sync: false

      - key: SUPABASE_PRODUCT_BUCKET
        sync: false

      - key: SUPABASE_WEBSITE_BUCKET
        sync: false